// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RemotePublish
{
    internal sealed partial class Vsix
    {
        public const string Id = "RemotePublish.98f436e9-4f71-45de-8719-b94c5bbb6485";
        public const string Name = "RemotePublish";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
