// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace RemotePublish
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RemotePublishString = "df556fec-5f81-442c-ae76-5165c0cf5949";
        public static Guid RemotePublish = new Guid(RemotePublishString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}